apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-eshop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: eshop-staging
    server: https://kubernetes.default.svc
  project: eshop-staging
  source:
    helm:
      valueFiles:
        - values.yaml
    path: app/eshop
    repoURL: https://github.com/J0hn-B/eshop-aks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
