kind: Namespace
apiVersion: v1
metadata:
  name: chaos-testing
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress-basic 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
# Eshop namespace
kind: Namespace
apiVersion: v1
metadata:
  name: eshop-staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
kind: Namespace
apiVersion: v1
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
