apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  annotations:
spec:
  destination:
    namespace: ingress-basic 
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "controller.service.loadBalancerIP"
        value: "{{ .Values.controller.service.loadBalancerIP }}"
        forceString: true # ensures that value is treated as a string
      valueFiles:
      - values.yaml
    path: k8s/k8s-charts/ingress-nginx
    repoURL: https://github.com/J0hn-B/eshop-aks.git
    targetRevision: HEAD
  syncPolicy: {}
