apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  annotations:
spec:
  destination:
    namespace: ingress-basic 
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      valueFiles:
      - values.yaml
    path: k8s/k8s-charts/ingress-nginx
    repoURL: https://github.com/J0hn-B/eshop-aks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ingress-ip
  namespace: ingress-basic
spec:
  backendType: azureKeyVault
  keyVaultName: aks-rotation-key-vault
  data:
    - key: public-ip
      name: ingress-ip-01
      isBinary: true