apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ingress-ip
  namespace: ingress-basic
spec:
  backendType: azureKeyVault
  keyVaultName: aks-rotation-key-vault
  data:
    - key: ingress-ip-01
      name: public-ip
      property: value